from app.extraction.types import (
    ExtractionInput,
    ExtractionPayload,
)
from app.models.obligation import (
    AnnotationStatus,
    CanonicalNoticeAnnotation,
)


def payload_from_annotation(
    annotation: CanonicalNoticeAnnotation,
) -> ExtractionPayload:

    return ExtractionPayload(
        evidence_spans=annotation.evidence_spans,
        obligations=annotation.obligations,
    )


def validate_exact_evidence(
    payload: ExtractionPayload,
    raw_text: str,
) -> None:

    for evidence in payload.evidence_spans:

        if evidence.text not in raw_text:
            raise ValueError(
                "Evidence span is not an exact "
                "substring of raw_text: "
                f"{evidence.text!r}"
            )


def build_prediction(
    notice: ExtractionInput,
    payload: ExtractionPayload,
    method: str,
) -> CanonicalNoticeAnnotation:

    validate_exact_evidence(
        payload,
        notice.raw_text,
    )

    return CanonicalNoticeAnnotation(
        schema_version="0.1",

        annotation_status=(
            AnnotationStatus.DRAFT
        ),

        annotator_id=method,

        notice_id=notice.notice_id,
        version_id=notice.version_id,

        source=notice.source,

        title=notice.title,
        raw_text=notice.raw_text,

        publication_time=(
            notice.publication_time
        ),

        observed_at=notice.observed_at,

        url=notice.url,

        content_hash=notice.content_hash,

        evidence_spans=(
            payload.evidence_spans
        ),

        obligations=payload.obligations,

        temporal_relations=[],

        notes=(
            f"Automatic prediction "
            f"generated by {method}."
        ),
    )