import re
import unicodedata
from difflib import SequenceMatcher

from app.extraction.types import ExtractionPayload


def normalize_for_matching(text: str) -> str:
    text = unicodedata.normalize("NFC", text)

    text = text.replace("–", "-")
    text = text.replace("—", "-")
    text = text.replace("→", "->")

    text = re.sub(r"\s+", " ", text)

    return text.strip().casefold()


def split_raw_segments(raw_text: str) -> list[str]:
    segments = []

    # First preserve lines because DUT notices often
    # contain useful line-level evidence.
    for line in raw_text.splitlines():
        line = line.strip()

        if line:
            segments.append(line)

    # Also create sentence-like candidates.
    for piece in re.split(
        r"(?<=[.;!?])\s+",
        raw_text,
    ):
        piece = piece.strip()

        if piece:
            segments.append(piece)

    # Remove duplicates while preserving order.
    result = []
    seen = set()

    for item in segments:
        if item not in seen:
            seen.add(item)
            result.append(item)

    return result


def find_grounded_text(
    evidence_text: str,
    raw_text: str,
) -> str | None:

    # Perfect case.
    if evidence_text in raw_text:
        return evidence_text

    wanted = normalize_for_matching(
        evidence_text
    )

    if not wanted:
        return None

    candidates = split_raw_segments(
        raw_text
    )

    best_text = None
    best_score = 0.0

    for candidate in candidates:
        normalized_candidate = (
            normalize_for_matching(
                candidate
            )
        )

        # Same content except spacing/unicode punctuation.
        if wanted == normalized_candidate:
            return candidate

        # Model quote may be a substring of the real sentence.
        if (
            wanted in normalized_candidate
            or normalized_candidate in wanted
        ):
            score = (
                min(
                    len(wanted),
                    len(normalized_candidate),
                )
                / max(
                    len(wanted),
                    len(normalized_candidate),
                )
            )

            if score > best_score:
                best_score = score
                best_text = candidate

        similarity = SequenceMatcher(
            None,
            wanted,
            normalized_candidate,
        ).ratio()

        if similarity > best_score:
            best_score = similarity
            best_text = candidate

    # Keep this deliberately strict.
    if best_score >= 0.88:
        return best_text

    return None


def ground_evidence(
    payload: ExtractionPayload,
    raw_text: str,
) -> ExtractionPayload:

    repaired = payload.model_copy(
        deep=True
    )

    for evidence in repaired.evidence_spans:

        grounded = find_grounded_text(
            evidence.text,
            raw_text,
        )

        if grounded is None:
            raise ValueError(
                "Could not safely ground "
                "evidence to raw_text: "
                f"{evidence.text!r}"
            )

        # IMPORTANT:
        # final value is copied from raw_text,
        # not generated by the LLM.
        evidence.text = grounded

        start = raw_text.find(
            grounded
        )

        if start >= 0:
            evidence.start_char = start
            evidence.end_char = (
                start + len(grounded)
            )

    return repaired
def sanitize_grounded_payload(
    payload: ExtractionPayload,
    raw_text: str,
) -> ExtractionPayload:

    repaired = payload.model_copy(
        deep=True
    )

    valid_ids: set[str] = set()
    grounded_spans = []

    # --------------------------------------------------
    # 1. Ground every evidence span.
    #    Unsupported/hallucinated evidence is discarded.
    # --------------------------------------------------

    for evidence in repaired.evidence_spans:

        grounded = find_grounded_text(
            evidence.text,
            raw_text,
        )

        if grounded is None:
            continue

        evidence.text = grounded

        start = raw_text.find(
            grounded
        )

        if start >= 0:
            evidence.start_char = start
            evidence.end_char = (
                start + len(grounded)
            )

        valid_ids.add(
            evidence.evidence_id
        )

        grounded_spans.append(
            evidence
        )

    repaired.evidence_spans = (
        grounded_spans
    )

    # --------------------------------------------------
    # 2. Remove references to evidence that was rejected.
    # --------------------------------------------------

    def filter_refs(obj) -> bool:

        if obj is None:
            return False

        obj.evidence_span_ids = [
            evidence_id
            for evidence_id
            in obj.evidence_span_ids
            if evidence_id in valid_ids
        ]

        return bool(
            obj.evidence_span_ids
        )

    cleaned_obligations = []

    for obligation in repaired.obligations:

        # Action is mandatory semantic content.
        # No trustworthy evidence => drop whole obligation.
        if not filter_refs(
            obligation.action
        ):
            continue

        if obligation.audience is not None:
            if not filter_refs(
                obligation.audience
            ):
                obligation.audience = None

        if obligation.deadline is not None:
            if not filter_refs(
                obligation.deadline
            ):
                obligation.deadline = None

        if obligation.amount is not None:
            if not filter_refs(
                obligation.amount
            ):
                obligation.amount = None

        if obligation.location is not None:
            if not filter_refs(
                obligation.location
            ):
                obligation.location = None

        obligation.required_documents = [
            document
            for document
            in obligation.required_documents
            if filter_refs(document)
        ]

        obligation.exceptions = [
            exception
            for exception
            in obligation.exceptions
            if filter_refs(exception)
        ]

        cleaned_obligations.append(
            obligation
        )

    repaired.obligations = (
        cleaned_obligations
    )

    # --------------------------------------------------
    # 3. Remove valid-but-unused evidence as well.
    # --------------------------------------------------

    referenced_ids: set[str] = set()

    for obligation in repaired.obligations:

        if obligation.audience:
            referenced_ids.update(
                obligation
                .audience
                .evidence_span_ids
            )

        referenced_ids.update(
            obligation
            .action
            .evidence_span_ids
        )

        if obligation.deadline:
            referenced_ids.update(
                obligation
                .deadline
                .evidence_span_ids
            )

        if obligation.amount:
            referenced_ids.update(
                obligation
                .amount
                .evidence_span_ids
            )

        if obligation.location:
            referenced_ids.update(
                obligation
                .location
                .evidence_span_ids
            )

        for document in (
            obligation.required_documents
        ):
            referenced_ids.update(
                document.evidence_span_ids
            )

        for exception in (
            obligation.exceptions
        ):
            referenced_ids.update(
                exception.evidence_span_ids
            )

    repaired.evidence_spans = [
        evidence
        for evidence
        in repaired.evidence_spans
        if evidence.evidence_id
        in referenced_ids
    ]

    return repaired